# SPDX-License-Identifier: MPL-2.0
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "twingate-connector.serviceAccountName" . }}
  labels:
    {{- include "twingate-connector.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
